version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
